apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwietoapp
  labels:
    app: kwieto
spec:
  type: LoadBalancer
  replicas: 2
  selector:
    matchLabels:
      app: kwieto
  template:
    metadata:
      labels:
        app: kwieto
    spec:
      containers:
      - name: kwieto
        image: kwieto/test
        ports:
        - containerPort: 6969
