apiVersion: apps/v1
kind: Deployment
metadata:
  name: kwietoapp
  labels:
    app: kwieto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kwieto
  template:
    metadata:
      labels:
        app: kwieto
    spec:
      containers:
        - name: kwieto
          image: kwieto/test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
